{
 "title": "Coralogix configuration",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(cx_configuration,account)"
    }
   },
   {
    "name": "team_id",
    "label": "team_id",
    "query": {
     "query": "label_values(cx_configuration,team_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"alert\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts - active",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"alert\",active=\"true\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Webhooks - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"webhook\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "alert types distribution - total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"alert\"}[1d])) by (alert_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "alert types distribution - active",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{type=\"alert\",account=~\"$account\",team_id=~\"$team_id\",active=\"true\"}[1d])) by (alert_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "webhooks distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{type=\"webhook\",account=~\"$account\",team_id=~\"$team_id\"}[1d])) by (webhook_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Parsing rules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Rules group - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"rules_group\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rules - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"parsing_rule\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parsing rules distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"parsing_rule\"}[1d])) by (parsing_rule_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TCO policies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Logs policies - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"tco_policy\",policy_type=\"LOGS\"}[1d])) by (priority)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spans policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"tco_policy\",policy_type=\"SPANS\"}[1d])) by (priority)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCO overrides",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"tco_overrides\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "e2m", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Log2Metics - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"e2m\",e2m_type=\"E2M_TYPE_LOGS2METRICS\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spans2Metics - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"e2m\",e2m_type=\"E2M_TYPE_SPANS2METRICS\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "apm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "apm services - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"apm\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "recording rules - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"recording_rule\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLOs - total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"slo\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apm technnology distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{type=\"apm\",account=~\"$account\",team_id=~\"$team_id\"}[1d])) by (technology)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apm service type distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{type=\"apm\",account=~\"$account\",team_id=~\"$team_id\"}[1d])) by (service_type)",
     "legendFormat": "{{service_type}}"
    }
   ]
  },
  { "title": "Dashboards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Coralogix (custom) dashboards - total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"cx_dashboard\",widget_type=''}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coralogix (custom) widgets - total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"cx_widget\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grafana folders - total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"grafana_folder\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grafana dashboards - total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"grafana_dashboard\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grafana panels - total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{account=~\"$account\",team_id=~\"$team_id\",type=\"grafana_panel\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coralogix (Csutom) widgets distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{type=\"cx_widget\",account=~\"$account\",team_id=~\"$team_id\"}[1d])) by (widget_type)",
     "legendFormat": "{{service_type}}"
    }
   ]
  },
  {
   "title": "grafana panels distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 10, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(cx_configuration{type=\"grafana_panel\",account=~\"$account\",team_id=~\"$team_id\"}[1d])) by (panel_type)",
     "legendFormat": "{{service_type}}"
    }
   ]
  }
 ]
}